<?php

declare(strict_types=1);
/**
 * This file is part of Marketing PHP SDK.
 *
 * @link     https://github.com/westng/oceanengine-sdk-php
 * @document https://github.com/westng/oceanengine-sdk-php
 * @contact  westng
 * @license  https://github.com/westng/oceanengine-sdk-php/blob/main/LICENSE
 */

namespace Api\JuLiangAds\SiteBuilder\AutoGeneratedPages;

use Core\Profile\RpcRequest;

/**
 * 更新落地页组站点状态.
 *
 * 通过此接口，用户可以修改落地页组站点的启用状态。
 */
class ToolsLandingGroupSiteOptStatusUpdate extends RpcRequest
{
    protected string $url = '/2/tools/landing_group/site_opt_status/update/';

    protected string $method = 'POST';

    protected string $content_type = 'application/json';

    /**
     * 广告主ID.
     */
    protected int $advertiser_id;
}
