<?php

declare(strict_types=1);
/**
 * This file is part of Marketing PHP SDK.
 *
 * @link     https://github.com/westng/oceanengine-sdk-php
 * @document https://github.com/westng/oceanengine-sdk-php
 * @contact  westng
 * @license  https://github.com/westng/oceanengine-sdk-php/blob/main/LICENSE
 */

namespace Api\JuLiangAds\SiteBuilder\AutoGeneratedPages;

use Core\Profile\RpcRequest;

/**
 * 获取落地页组.
 *
 * 通过此接口，用户可以获取落地页组以及站点的基本信息。
 *
 * 落地页组信息会包括落地页组 ID、落地页组名称、落地页组 URL、落地页组状态、流量分配方式；
 * 站点列表信息会包括成员 ID（即站点在落地页组中的唯一标识）、站点 ID、站点URL、站点启用状态、站点审核状态。
 */
class ToolsLandingGroupGet extends RpcRequest
{
    protected string $url = '/2/tools/landing_group/get/';

    protected string $method = 'GET';

    protected string $content_type = 'application/json';

    /**
     * 广告主ID.
     */
    protected int $advertiser_id;
}
