<?php

declare(strict_types=1);
/**
 * This file is part of Marketing PHP SDK.
 *
 * @link     https://github.com/westng/oceanengine-sdk-php
 * @document https://github.com/westng/oceanengine-sdk-php
 * @contact  westng
 * @license  https://github.com/westng/oceanengine-sdk-php/blob/main/LICENSE
 */

namespace Api\JuLiangAds\SiteBuilder\AutoGeneratedPages;

use Core\Exception\InvalidParamException;
use Core\Helper\RequestCheckUtil;
use Core\Profile\RpcRequest;

/**
 * 更新落地页组信息.
 *
 * 通过此接口，用户可以更新落地页组的基本信息。
 *
 * 落地页组信息会包括落地页组 ID、落地页组名称、落地页组 URL、落地页组状态、流量分配方式；
 * 站点列表信息会包括成员 ID（即站点在落地页组中的唯一标识）、站点 ID、站点URL、站点启用状态、站点审核状态。
 */
class ToolsLandingGroupUpdate extends RpcRequest
{
    protected string $url = '/2/tools/landing_group/update/';

    protected string $method = 'POST';

    protected string $content_type = 'application/json';

    /**
     * 广告主ID.
     */
    protected int $advertiser_id;

    /**
     * @return $this
     */
    public function setArgs(mixed $args): static
    {
        foreach ($args as $key => $value) {
            $this->params[$key] = $this->{$key} = $value;
        }
        return $this;
    }

    /**
     * @throws InvalidParamException
     */
    public function check(): void
    {
        RequestCheckUtil::checkNotNull($this->advertiser_id, 'advertiser_id');
    }
}
